version: '3.7'

x-database-variables: &database-variables
  MYSQL_DATABASE: 'db'
  MYSQL_USER: 'user'
  MYSQL_PASSWORD: 'password'
  MYSQL_ROOT_PASSWORD: 'password'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    container_name: graphql-server
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    restart: always
    env_file: ./server/.env
    environment:
      <<: *database-variables
      MYSQL_HOST: mysql
    networks:
      - backend
      - frontend
  react:
    build:
      context: ./web
    ports:
      - "3000:3000"
    container_name: react
    stdin_open: true
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules
    networks:
      - frontend
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    networks:
      - backend
    environment:
      <<: *database-variables
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
networks:
  backend:
  frontend:
volumes:
  db:
